//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2124802010277_LeTuanKiet_CuoiKy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiTapRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiTapRoom()
        {
            this.ChiTietBaiTapRooms = new HashSet<ChiTietBaiTapRoom>();
            this.FileMotaBtRooms = new HashSet<FileMotaBtRoom>();
        }
    
        public int IdBTRoom { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> IdRoom { get; set; }
        public Nullable<double> TyLeNop { get; set; }
        public Nullable<double> DiemCaoNhat { get; set; }
        public Nullable<double> DiemTrungBinh { get; set; }
        public string NoiDungBaiTap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBaiTapRoom> ChiTietBaiTapRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileMotaBtRoom> FileMotaBtRooms { get; set; }
    }
}
