//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2124802010277_LeTuanKiet_CuoiKy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBaiTapRoom
    {
        public int IdChiTiet { get; set; }
        public Nullable<int> IdNguoiNop { get; set; }
        public Nullable<int> IdBTRoom { get; set; }
        public string FileNop { get; set; }
        public Nullable<System.DateTime> NgayNop { get; set; }
        public Nullable<double> Diem { get; set; }
    
        public virtual BaiTapRoom BaiTapRoom { get; set; }
    }
}
